from .config import DATABASE_URL
from .constants import (
    DOMAIN_BUCKET_WEIGHT,
    DOMAIN_FIT_WEIGHT,
    DOMAIN_INTENT_PATTERNS,
    DOMAIN_PROTOTYPES,
    DOMAIN_SKILL_TERMS,
    DOMAINS,
    JD_PATTERNS,
    NON_JD_PATTERNS,
    PRIORITY_PATTERNS,
    RELEVANCE_QUERIES,
    SEMANTIC_RELEVANCE_GATE,
    WEIGHT_KEYWORD,
    WEIGHT_SEMANTIC,
    WEIGHT_SKILL,
)
from .embeddings import (
    classify_domain,
    compute_resume_domain_fit,
    get_model,
    has_analyst_role_signals,
    has_core_nontech_role_signals,
    has_software_role_signals,
)
from .jd_store import (
    chunk_is_priority,
    ensure_table,
    extract_and_store_jds,
    extract_and_store_jds_from_zip,
    fetch_jds_by_domain,
    fetch_jds_from_folder,
    filter_relevant_chunks,
    get_db_connection,
    get_text_from_file,
    is_probable_jd,
    save_to_database,
    split_into_logical_chunks,
)
from .matching import (
    compute_ats_score,
    compute_semantic_scores,
    jd_matches_domain,
    match_resume,
    match_resume_against_jds,
    match_resume_all_domains,
    match_resume_all_domains_against_jds,
    score_keyword_density,
    score_resume_against_jds,
    score_skill_overlap,
    SUMMARY_TOP_K,
)
